version: '3.7'

services:
  mysql:
    build: .docker/mysql
    container_name: mysql-foodtruck-api
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - bubble
    environment:
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: foodtruck

  foodtruck:
    build: .
    container_name: foodtruck-api
    restart: always
    tty: true
    ports:
      - "8080:8080"
    networks:
      - bubble
    environment:
      DATABASE_HOST: mysql-foodtruck-api
      DATABASE_PORT: 3306
    depends_on:
      - mysql

networks:
  bubble:

volumes:
  db: