version: '3'

services:
  mysql:
    build: .docker/mysql
    container_name: mysql-foodtruck-api
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - /home/charles/dbs/mysql/:/var/lib/mysql
    networks:
      - foodtruck-network

  foodtruck:
    build: .
    container_name: foodtruck-api
    restart: always
    tty: true
    ports:
      - "8080:8080"
    networks:
      - foodtruck-network
    environment:
      DATABASE_HOST: mysql-foodtruck-api
      DATABASE_PORT: 3306
    depends_on:
      - mysql
#    entrypoint: dockerize -wait tcp://mysql-foodtruck-api:3306 -timeout 40s

networks:
  foodtruck-network:
    external: true